name: Run tests with Geonetwork service

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      geonetwork:
        image: geonetwork:3.10.4
        env:
          DATA_DIR: /catalog-data
          TZ: Europe/Paris
        ports:
          - 8081:8080

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for Geonetwork to start
        run: |
          echo "Waiting for Geonetwork to start..."
          timeout 300 bash -c "until curl http://localhost:8081/geonetwork; do sleep 10; done"

      - name: Run tests
        run: |
          pytest tests/
